/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#434654",
        "primary-container": "#2d56cf",
        "on-surface": "#e2e2e2",
        "on-error": "#690005",
        "surface-dim": "#121414",
        "secondary-container": "#48494c",
        "tertiary-fixed": "#e4e2e4",
        "secondary": "#c7c6ca",
        "on-primary-fixed-variant": "#003ab2",
        "tertiary": "#c8c6c8",
        "surface-variant": "#333535",
        "surface-container-lowest": "#0c0f0f",
        "inverse-on-surface": "#2f3131",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c4c5d6",
        "on-tertiary-fixed": "#1b1b1d",
        "surface-container-high": "#282a2b",
        "inverse-surface": "#e2e2e2",
        "inverse-primary": "#2a54cd",
        "secondary-fixed-dim": "#c7c6ca",
        "on-primary-container": "#d3daff",
        "on-primary-fixed": "#001550",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#474649",
        "on-primary": "#00277f",
        "primary": "#b6c4ff",
        "background": "#121414",
        "on-tertiary": "#303032",
        "surface-container": "#1e2020",
        "on-background": "#e2e2e2",
        "outline": "#8e909f",
        "surface-bright": "#38393a",
        "tertiary-container": "#616062",
        "surface": "#121414",
        "on-secondary": "#2f3034",
        "on-secondary-fixed-variant": "#46474a",
        "surface-container-low": "#1a1c1c",
        "secondary-fixed": "#e3e2e6",
        "on-secondary-fixed": "#1a1b1f",
        "on-secondary-container": "#b8b8bc",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#b6c4ff",
        "surface-tint": "#b6c4ff",
        "tertiary-fixed-dim": "#c8c6c8",
        "primary-fixed": "#dce1ff",
        "on-tertiary-container": "#dedbdd",
        "surface-container-highest": "#333535",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "3rem",
        "sidebar-width": "16rem",
        "topbar-height": "3.25rem",
        "gutter": "1px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "code": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "code": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
